stages:
  - build
  - test
  - deploy
job1:
  stage: build
  script:
    - ls
    - gradle clean build -x test
job2:
  stage: test
  script:
    - gradlew test
job3:
  stage: deploy
  script:
    - git_stats generate -o build/reports/git
    - lftp ftp://heber_15054748:zaza666@ftp.hebergratuit.net -e "mirror -e -R --parallel=20 --only-newer --verbose build/docs /htdocs/hive/docs; quit"
    - lftp ftp://heber_15054748:zaza666@ftp.hebergratuit.net -e "mirror -e -R --parallel=20 --only-newer --verbose build/reports /htdocs/hive/reports; quit"