network.host: 127.0.0.1
transport.tcp.port: 3307
http.port: 8080
http.host : localhost
discovery.zen.ping.multicast.enabled: false
discovery.zen.ping.unicast.hosts: []
path.data: /home/xavier/workspaceQaobee/qaobee-hive/diy/elasticsearch/data
http.type: com.sonian.elasticsearch.http.jetty.JettyHttpServerTransportModule
sonian.elasticsearch.http.jetty: 
	config: jetty.xml,jetty-hash-auth.xml,jetty-restrict-all.xml

