network.host: ${OPENSHIFT_DIY_IP}
transport.tcp.port: 3306
http.port: ${OPENSHIFT_DIY_PORT}
discovery.zen.ping.multicast.enabled: false
discovery.zen.ping.unicast.hosts: []
path.data: ${OPENSHIFT_DATA_DIR}
http.type: com.sonian.elasticsearch.http.jetty.JettyHttpServerTransportModule
sonian.elasticsearch.http.jetty: 
	config: jetty.xml,jetty-hash-auth.xml,jetty-restrict-all.xml
	publish_host: ${OPENSHIFT_DIY_PORT}